Attribute VB_Name = "Module1"
'Dim w As Double   '무게
'Dim S As Double   '면적
'Dim p As Double   '공기밀도
'Dim V As Double   '속도
'Dim wl As Double  '윙로딩
'Dim q As Double   '동압

'Dim b As Double
'Dim c As Double
'Dim ll As Double  'CL
'Dim sl As Double  'Cl
'Dim Cl As Double  '양력계수
'Dim be As Double  '비율  <-쓸모없다.(양력에서는)


Dim w%   '무게
Dim S%
Dim p%
Dim V%
Dim wl%
Dim q%

Dim b%
Dim c%
Dim ll%
Dim sl%
Dim Cl%
Dim be%



