Attribute VB_Name = "Module1"
Public instring As String
Public q As String
Public i As String
Public Rcv As String
Public data As String
Public p00 As String
Public p01 As String
Public p02 As String
Public p05 As String
Public p06 As String
Public p07 As String
Public p08 As String
Public p09 As String
Public p10 As String
Public p11 As String
Public p12 As String
Public webQ As String
Public w As Integer
Public 에러접수 As String
Public dial1 As String
Public dial2 As String
Public dial3 As String
Public SMS As String
Public dialcheck1 As String
Public dialcheck2 As String
Public dialcheck3 As String
Public t As Integer
Public set1 As String
Public set2 As String
Public set3 As String
Public set4 As String
Public modemcom As Integer
Public smsmsg As String

Public 설정다운로드 As String
Public site As String

