VERSION 5.00
Begin VB.Form frm1 
   ClientHeight    =   8760
   ClientLeft      =   60
   ClientTop       =   60
   ClientWidth     =   11895
   ControlBox      =   0   'False
   LinkTopic       =   "Form1"
   ScaleHeight     =   8760
   ScaleWidth      =   11895
   StartUpPosition =   3  'Windows ±âº»°ª
End
Attribute VB_Name = "frm1"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = False
